### PR TITLE
feat(tournament): allow show tournament function params to be set

### PR DESCRIPTION
**Pull request by jvinai**

### CODE REVIEW

**Comment by ColinDTaylor** [comment]
Oh sweet, I've been needing this but haven't had the time to implement it myself. Is there any way you could give "show participants" the same treatment?

**Comment by jvinai** [comment]
Yes i can do that too.

I forget to say, to use default parameters the lowest nodejs version will be 6.8.1, is that ok or you prefer i use `assign` ?

**Comment by ColinDTaylor** [comment]
My project that uses this is already running 6.8.1, so that's completely fine for me, thanks!

**Comment by alanhhwong** [comment]
@jvinai will wait for your updated PR for "show participants" :)  thanks!

**Comment by jvinai** [comment]
Done :)

**Comment by jvinai** [comment]
I updated all functions with `params`

**Pull request merged**
